name : MERN CI/CD Pipeline

on:
  push:
    branches:
      -main 
  pull_request:
    branches:
      -main

jobs:
  build:
    name: Install Backend Dependencies
    run: npm init -y
    working-directory: ./backend