name: MERN CI/CD Pipeline

on:
  push:
    branches:
      - main  # Fixed spacing
  pull_request:
    branches:
      - main  # Fixed spacing

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest  # Specify the runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm init -y
          npm install 
      
      - name : Install frontend Dependencies
        run : |
          cd frontend
          npm init -y
          npm install